spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/seguranca01
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate

server:
  error:
    include-message: always
    include-binding-error: always
    include-stacktrace: on_param

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
